apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-comet-optimizer
spec:
  template:
    spec:
      containers:
      - name: start-optimizer
        image: comet-optimizer
        env:
        - name: COMET_API_KEY
          value: "REPLACE_WITH_YOUR_API_KEY"
        - name: COMET_WORKSPACE
          value: "REPLACE_WITH_YOUR_WORKSPACE"
        - name: COMET_PROJECT_NAME
          value: "REPLACE_WITH_YOUR_PROJECT_NAME"
        command: ['python', 'initialize_optimizer.py']
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4